#!/usr/bin/bash
pip install -q --upgrade pip==25.2
if ! command -v pip-compile > /dev/null; then
  pip install -q --upgrade pip-tools
fi
if [ ! -f "requirements.txt" ]; then
  pip-compile -q --strip-extras --no-emit-index-url
fi
pip-sync
